eurostat_dictionary = {
    'BE' : 'Belgium',
    'BG' : 'Bulgaria',
    'CZ' : 'Czechia',
    'DK' : 'Denmark',
    'DE' : 'Germany',
    'EE' : 'Estonia',
    'IE' : 'Ireland',
    'EL' : 'Greece',
    'ES' : 'Spain',
    'FR' : 'France',
    'HR' : 'Croatia',
    'IT' : 'Italy',
    'CY' : 'Cyprus',
    'LV' : 'Latvia',
    'LT' : 'Lithuania',
    'LU' : 'Luxembourg',
    'HU' : 'Hungary',
    'MT' : 'Malta',
    'NL' : 'Netherlands',
    'AT' : 'Austria',
    'PL' : 'Poland',
    'PT' : 'Portugal',
    'RO' : 'Romania',
    'SI' : 'Slovenia',
    'SK' : 'Slovakia',
    'FI' : 'Finland',
    'SE' : 'Sweden',
    'UK' : 'United Kingdom',
    'IS' : 'Iceland',
    'NO' : 'Norway',
    'LI' : 'Liechtenstein',
    'CH' : 'Switzerland',
    'ME' : 'Montenegro',
    'MK' : 'North Macedonia',
    'AL' : 'Albania',
    'RS' : 'Serbia',
    'TR' : 'Turkey',
    'BA' : 'Bosnia and Herzegovina',
    'XK' : 'Kosovo',
    'RU' : 'Russia',
    'AM' : 'Armenia',
    'AZ' : 'Azerbaijan',
    'DZ' : 'Algeria',
    'EG' : 'Egypt',
    'IL' : 'Israel',
    'JO' : 'Jordan',
    'BY' : 'Belarus',
    'MD' : 'Moldova',
    'LB' : 'Lebanon',
    'LY' : 'Libya',
    'MA' : 'Morocco',
    'PS' : 'Palestine',
    'GE' : 'Georgia',
    'UA' : 'Ukraine',
    'SY' : 'Syria',
    'TN' : 'Tunisia',
    'AR' : 'Argentina',
    'AU' : 'Australia',
    'BR' : 'Brazil',
    'CA' : 'Canada',
    'HK' : 'Hong Kong',
    'IN' : 'India',
    'JP' : 'Japan',
    'MX' : 'Mexico',
    'NG' : 'Nigeria',
    'NZ' : 'New Zealand',
    'SG' : 'Singapore',
    'ZA' : 'South Africa',
    'KR' : 'South Korea',
    'TW' : 'Taiwan',
    'US' : 'United States',
    'CN_X_HK' : 'China (except Hong Kong)'
    }

